# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-3559036-exjobb35/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tsbg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    set rt::enableVHDL2008 1
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1
    /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado
  } {
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/raminfr.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_receiver.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_regs.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_rfifo.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_sync_flops.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_tfifo.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_top.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_transmitter.v
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_uart16550_1.5.5-r1/uart_wb.v
      /home/pe1576su/Desktop/slice/microwatt/litedram/generated/nexys-video/litedram_core.v
      /home/pe1576su/Desktop/slice/microwatt/liteeth/generated/nexys-video/liteeth_core.v
      /home/pe1576su/Desktop/slice/microwatt/litesdcard/generated/xilinx.100e6/litesdcard_core.v
    }
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/decode_types.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/wishbone_types.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/common.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fetch1.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/predecode.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/decode1.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/helpers.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/decode2.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/register_file.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/cr_file.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/crhelpers.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/ppc_fx_insns.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/sim_console.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/logical.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/countbits.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/bitsort.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/control.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/execute1.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpu.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/loadstore1.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/mmu.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/dcache.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/divider.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/rotator.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/pmu.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/writeback.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/insn_helpers.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/core.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/icache.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/plrufn.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/cache_ram.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/core_debug.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/utils.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/clk_gen_plle2.vhd
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/top-nexys-video.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/wishbone_arbiter.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/wishbone_debug_master.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/wishbone_bram_wrapper.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/soc.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/xics.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/gpio.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/syscon.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/sync_fifo.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/spi_rxtx.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/spi_flash_ctrl.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/git.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/main_bram.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/soc_reset.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/pp_fifo.vhd
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/pp_soc_uart.vhd
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/fpga/pp_utilities.vhd
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/nonrandom.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/dmi_dtm_xilinx.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/xilinx-mult.vhdl
      /home/pe1576su/Desktop/slice/microwatt/build/microwatt_0/nexys_video-vivado/src/microwatt_0/xilinx-mult-32s.vhdl
      /home/pe1576su/Desktop/slice/microwatt/litedram/generated/nexys-video/litedram-initmem.vhdl
      /home/pe1576su/Desktop/slice/microwatt/litedram/extras/litedram-wrapper-l2.vhdl
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top toplevel
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3559036-exjobb35/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -param {
  { memory_size 0 }
  { cpus 2 }
  { clk_frequency 9000000 }
  { use_litedram 1'b1 }
  { use_liteeth 1'b1 }
  { use_litesdcard 1'b0 }
  { disable_flatten_core 1'b0 }
  { no_bram 1'b1 }
  { spi_flash_offset 10485760 }
  { log_length 2048 }
  { uart_is_16550 1'b1 }
  { has_fpu 1'b1 }
  { has_btc 1'b1 }
} -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
